src/Prismic/SearchForm.php
These patches clarify some SearchForm documentation, and also ensure
that the chainable methods always return a new object, for the sake of
consistency.
See https://github.com/prismicio/php-kit/pull/84 for some related
discussion
=> SearchForm behaviour/doc reconciliation, doc clarification

src/Prismic/Cache/CacheInterface.php, src/Prismic/Cache/DefaultCache.php, src/Prismic/Cache/NoCache.php, src/Prismic/SearchForm.php, tests/Prismic/CacheTest.php
Rationale: though to my knowledge Prismic never caches a null value,
it is possible for caches to store null and for that to be different
from the key not existing in cache. Adding a has method to the
CacheInterface allows developers to provide a more reliable way to
tell these apart, if available for the cache backend. This also leads
to a fuller cache interface. In many cases (especially if the value is
large, as some will be in Prismic) checking if a key exists in cache
can be much faster than retrieving the value and checking against
null.
=> Add CacheInterface#has method

src/Prismic/Fragment/Date.php
Without forcing time to midnight, date fragments (which don't provide
a time, only date) come back as DateTimes with the current time of
day.
=> Date#asDateTime: force time to midnight

src/Prismic/Cache/CacheInterface.php, src/Prismic/SearchForm.php, tests/Prismic/LesBonnesChosesTest.php
This reverts most of commit 9890bb7f08c573909d1c9d4d5e8dea512a5b677c,
and its author @gsteel will need to update his Memcached
CacheInterface implementation after this patch.
There is some discussion at
https://github.com/prismicio/php-kit/issues/83
Before this patch, most cache keys were being hashed before being sent
to the CacheInterface, to limit their length.
However, though some cache backends have low key length limits, many
(including APC, which Prismic supports, and Redis and more) do not.
For these, the hashing operation is not required. It is preferable
when administrating and debugging a cache for the keys not to be
hashed, since when hashed the keys are no longer sortable in an
appreciable way and there is no clue to what the corresponding cache
values might contain.
Notably, …
=> Don't hash cache keys

src/Prismic/Fragment/StructuredText.php
* Fixes issue where getting a StructuredText fragment asHtml() would
remove character encoding from the string
=> Add character encoding to htmlentities

src/Prismic/Predicates.php
This method was generating an invalid predicate string.
=> Fix Predicates::dateBetween method

src/Prismic/Api.php
Allow the default HTTP adapter configuration to be retrieved, and allow such a configuration object to be passed to the defaultHttpAdapter method. This allows
- configuration to be tweaked before the default adapter is used
- completely separate configuration to be used with the default adapter
- default configuration to be used with a custom adapter
- tweaked default configuration to be used with a custom adapter
=> Add HTTP adapter configuration getter, allow to be passed to defaultHttpAdapter

composer.json, src/Prismic/Api.php, src/Prismic/SearchForm.php
Related to issue #111.
I've got a Symfony 2.7 project and I was unable to install the php-kit due to a conflict with Guzzle. egeloen/http-adapter 0.8.0 doesn't conflict, but the API is slightly different and then caused the PHP kit to stop working.
This pull request updates the library to 0.8.0 and fixes the internal parts of the Prismic API class that stopped working as a result. From what I can see it shouldn't affect code using the Prismic API classes, but those who've worked on this code for a while might be able to shed more light on this.
All the unit tests pass with my changes.
=> Update egeloen/http-adapter to 0.8.0. Updated code for API changes in egeloen/http-adapter. All tests pass.

src/Prismic/Api.php
If the link resolver is unable to resolve the URL for the preview document and returns null, return the given default URL as opposed to the null received from the link resolver.
i.e - at the moment, I redirect to whatever URL Api::previewSession returns. If I get a null, my framework complains about a header with no value. I think this method should always return a string as the docs state, so whilst I could easily check the return value for this, I shouldn't have to…
=> Return $defaultUrl in Api::previewSession()

src/Prismic/Api.php
It is now possible to specify a custom type as Single (only one document of this type can be created), this PR adds a helper to easily retrieve documents of such types.
=> Add API.getSingle

src/Prismic/Api.php, tests/Prismic/ApiTest.php
If you want to use a search form for example without using Api::query, currently, you have to search $_COOKIE to check if you're in a preview or experiment.
=> Add public method to retrieve the current ref

composer.json, src/Prismic/Predicates.php, tests/Prismic/PredicatesTest.php, tests/Prismic/PublicationDatesTest.php, tests/fixtures/publication_dates.json
- Add `not` predicate
- Add tests on publication dates
- Require `symfony/event-dispatcher` and `phpunit` using caret instead of tilde since this form will accept any [semantic versioning](http://semver.org/)'s non-breaking version. (should resolves #128)
=> Add missing helpers and improve composer.json file (~ → ^)

src/Prismic/Api.php, tests/Prismic/ApiTest.php
Currently, Api::ref() will return the google experiment id as the ref which results in a 404 from the Prismic API. The ref needs to be retrieved from the running experiments by finding the experiment by it's Google ID and corresponding ref.
=> Experiment ref from cookie

src/Prismic/Fragment/Image.php, tests/Prismic/DocumentTest.php
Fix an undefined index notice when trying to access an image view that doesn’t exist
=> Fix ImageView undefined index

src/Prismic/Api.php, tests/Prismic/ApiTest.php
The experiment cookie value was previously being returned unmodified if found, therefore, users with an experiment cookie for a completed experiment would cause the library to request a ref that did not exist in the API. That was a bad thing.
=> Fixes an issue where a stale experiment cookie causes an Api 404

src/Prismic/Fragment/CompositeSlice.php, src/Prismic/Fragment/Slice.php, src/Prismic/Fragment/SliceInterface.php, tests/Prismic/SliceTest.php
Add SliceInterface to represent common traits of normal slices and composite slices.
Also added some missing properties to the Slice class declaration and type hinted FragmentInterface in the constructor.
=> Add Slice Interface

src/Prismic/Fragment/StructuredText.php
Fixes a bug that incorrectly displays an ordered list when it is the first item in a Structured Text field.
=> Fix ordered list bug

src/Prismic/Document.php, src/Prismic/Fragment/ImageView.php, src/Prismic/Fragment/Link/DocumentLink.php, src/Prismic/Fragment/Link/FileLink.php, src/Prismic/Fragment/Link/ImageLink.php, src/Prismic/Fragment/Link/WebLink.php, src/Prismic/Fragment/Span/HyperlinkSpan.php, src/Prismic/Fragment/StructuredText.php, src/Prismic/LinkResolver.php, tests/Prismic/FragmentsTest.php, tests/Prismic/StructuredTextTest.php, tests/fixtures/weblinks_targetblank.json
This updates the kit to add support for the target blank feature.
Here are the changes included:
- Parses the target if included in the link's JSON
- Adds link variable and getLink function to link objects
- Adds target output to WebLink, StructuredText, and ImageView asHtml serializers
- Adds tests for target blank
=> Add support for target blank

.travis.yml, src/Prismic/Api.php, tests/Prismic/ApiTest.php, tests/apc.ini
Added 2 methods and tests to determine whether the current session is a preview or an experiment.
The use-case for this is based around the idea that if you are caching rendered content separately to the cached api calls, you'll probably want to know if you're in the middle of a preview so that you can return fresh content to the editor. This is particularly relevant when you're working with content that doesn't directly relate to the document being previewed, for example cached layout elements/content.
Whilst the use case doesn't really hold for experiments, I don't think it hurts to have a helpful accessor that can tell you whether you're in experiment mode or not (?)
=> Detect Preview or Experiment Mode

composer.json
* "Warning: count(): Parameter must be an array or an object that implements
Countable"
* See https://github.com/guzzle/guzzle/issues/1973
=> Update Guzzle version to fix "Warning: count()..."

src/Prismic/Api.php, src/Prismic/ApiData.php, src/Prismic/Form.php
Using late static binding allows the developers to extend the original Api class and make some customizations.
With this change, developers can rename the cookie by simply doing like this:
```php
class CustomAPI extends Prismic\Api {
const PREVIEW_COOKIE = "my_custom_cookie";
}
CustomAPI::get('https://project.prismic....');
```
It can also add some logs or manipulation on top of the original class:
```php
class CustomAPI2 extends Prismic\Api {
public function query($q, $options = array()) {
$options['lang'] => $_COOKIE['my_custom_locale_cookie'];
return parent::query($q, $options);
}
}
CustomAPI::get('https://project.prismic....');
```
These 2 things are not possible currently because the `Api::get()` has the returning forcing to use the `Prismic\Api` class. The only alternative would be …
=> Updated API to use late static binding

src/Prismic/SimplePredicate.php, tests/Prismic/PredicatesTest.php
Since the last tagged release (5.1.1) the [boolean field](https://user-guides.prismic.io/en/articles/3456034-boolean-field) has been [released](https://prismic.io/blog/prismic-boolean-fields).
We've made good use of this and have come across an issue where this field is not serialised properly, passing through 1 and 0 instead of true and false.
I've added a simple test around this.
=> Serialize boolean values

README.md
This PR updates the build status badge in the readme file. Currently, the Badge links to an [old migrated page](https://travis-ci.org/github/prismicio/php-kit).
This small change points to the [new and correct url](https://app.travis-ci.com/github/prismicio/php-kit).
=> docs: update build status badge [skip ci]

README.md
The example shows the `getByUID` function being used with just the UID argument when the function also requires the document type.
=> Fix README example not including project type

src/Prismic/Dom/RichText.php, tests/Prismic/Dom/RichTextTest.php
This PR aims to solve Issue #152 
As mentioned by @cloakedninjas it does not make sense to have a trailing `\n` on the last block in `RichText::asText()`.
I implemented a solution like the one mentioned in the issue and updated and extended the Tests for the `asText` function.
=> fix (#152): remove last new line from rich text blocks

src/Prismic/Dom/RichText.php
Escapes the link target around images inside of a rich-text field which was introduced by #194
=> feat: escape link target around images

.github/workflows/ci.yml
This PR adds a basic GitHub Actions workflow to run tests.
It replaces the previous Travis CI workflow.
=> ci: add GitHub Actions CI config

src/Prismic/Api.php, src/Prismic/ApiData.php, tests/Prismic/ApiDataTest.php, tests/Prismic/ApiTest.php, tests/fixtures/data-without-bookmarks.json
This pull request marks the public methods for _bookmarks_ as @deprecated since the new version (which would be 5.4.0)!
It has to be done, as the field will be removed from the prismic api on February 12 2025 (see #209)
I added tests to ensure the methods will still work without the field beeing present.
They will simply return an empty array (or null, if checked for a specific bookmark).
=> Mark Bookmark Methods as Deprecated (From Discussions #209)
